enum HouseStatus {
    AVAILABLE = "AVAILABLE",
    RENTED = "RENTED",
    PENDING = "PENDING",
    DEPOSIT = "DEPOSIT",
}

enum HousePermissions {
    HOUSE_OWNER = "HOUSE_OWNER",
    READ_HOUSE = "READ_HOUSE",
    UPDATE_HOUSE = "UPDATE_HOUSE",
    DELETE_HOUSE = "DELETE_HOUSE",
    CREATE_ROOM = "CREATE_ROOM",
    READ_ROOM = "READ_ROOM",
    UPDATE_ROOM = "UPDATE_ROOM",
    DELETE_ROOM = "DELETE_ROOM",
    CREATE_BILL = "CREATE_BILL",
    READ_BILL = "READ_BILL",
    UPDATE_BILL = "UPDATE_BILL",
    DELETE_BILL = "DELETE_BILL",
    CREATE_SERVICE = "CREATE_SERVICE",
    READ_SERVICE = "READ_SERVICE",
    UPDATE_SERVICE = "UPDATE_SERVICE",
    DELETE_SERVICE = "DELETE_SERVICE",
    CREATE_EQUIPMENT = "CREATE_EQUIPMENT",
    READ_EQUIPMENT = "READ_EQUIPMENT",
    UPDATE_EQUIPMENT = "UPDATE_EQUIPMENT",
    DELETE_EQUIPMENT = "DELETE_EQUIPMENT",
}

export { HouseStatus, HousePermissions };
