openapi: "3.0.0"
security:
    - BearerAuth: []
paths: {}
info:
    title: API
    version: 1.0.0
components:
    schemas:
        TokenInvalid:
            type: object
            properties:
                code:
                    default: TOKEN_INVALID
                message:
                    default: Token is invalid
        TokenExpired:
            type: object
            properties:
                code:
                    default: TOKEN_EXPIRED
                message:
                    default: Token is expired

        ValidationError:
            type: object
            properties:
                code:
                    example: VALIDATION_ERROR
                message:
                    example: Validation error
                data:
                    type: array
                    items:
                        type: object
                        properties:
                            type:
                                type: string
                            value:
                                type: string
                            msg:
                                type: string
        UserInfo:
            type: object
            properties:
                id:
                    type: string
                    example: 231c665c-dc53-42c6-88cc-e36490cb52a8
                email:
                    type: string
                    example: example@gmail.com
                password:
                    type: string
                    example: $2b$10$FQ2zp5N2ix1rYlAjuQMkY.zbXQECUmeMp0x3D5lFrm6vT9QmoIfvy
                fullName:
                    type: string
                    example: John Doe
                gender:
                    type: string
                    enum:
                        - male
                        - female
                        - other
                    example: male
                phoneNumber:
                    type: string
                    example: 0123456789
                    maxLength: 11
                    pattern: ^0\d{9,10}$
                address:
                    type: string
                    example: 123 Nguyen Van Linh, District 7, Ho Chi Minh City
                    maxLength: 255
                birthday:
                    type: string
                    example: 1969-12-31
                    maxLength: 10
                    pattern: ^\d{4}-\d{2}-\d{2}$
                role:
                    type: string
                    example: user
                    enum:
                        - user
                        - admin
                type:
                    type: string
                    example: free
                    enum:
                        - free
                        - premium
                status:
                    type: integer
                    example: 1
                verify:
                    type: integer
                    example: 1
                firstLogin:
                    type: integer
                    example: 1
                createdAt:
                    type: string
                    example: 2024-09-19T16:20:09.000Z
                updatedBy:
                    type: string
                    example: 231c665c-dc53-42c6-88cc-e36490cb52a8
                updatedAt:
                    type: string
                    example: 2024-09-19T16:20:09.000Z

        GetUserNotFound:
            type: object
            properties:
                code:
                    default: GET_USER_NOT_FOUND
                message:
                    default: User not found

        CheckMailResetPassword:
            type: object
            properties:
                code:
                    default: CHECK_MAIL_RESET_PASSWORD
                message:
                    default: Check your mail to reset password
