openapi: "3.0.3"
info:
    title: Upload API
    version: 1.0.0

tags:
    - name: Upload
      description: File upload API

paths:
    /upload:
        post:
            summary: Upload a file
            description: Upload a file to the server
            tags:
                - Upload
            requestBody:
                required: true
                content:
                    multipart/form-data:
                        schema:
                            type: object
                            properties:
                                file:
                                    type: string
                                    format: binary
            responses:
                "200":
                    description: OK
                "400":
                    description: Bad Request
                "500":
                    description: Internal Server Error
