name: Send Telegram Message on Commit

on: [push]

jobs:
    notify-telegram:
        runs-on: ubuntu-latest
        steps:
            - name: Send message to Telegram
              env:
                  TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
                  TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_TO }}
                  COMMITTER: ${{ github.actor }} # The user who made the commit
                  COMMIT_MESSAGE: ${{ github.event.head_commit.message }} # Commit message
                  REPOSITORY: ${{ github.repository }} # Repository name
                  COMMIT_URL: ${{ github.event.head_commit.url }} # URL to the commit
                  COMMIT_SHA: ${{ github.sha }} # Commit SHA
              run: |
                  # Create message content with markdown
                  MESSAGE="🚀 *New Commit by*: *${COMMITTER}*%0A%0A\
                  📝 *Commit Message*: _${COMMIT_MESSAGE}_%0A%0A\
                  📂 *Repository*: [${REPOSITORY}](https://github.com/${REPOSITORY})%0A%0A\
                  🔗 *View Changes*: [Click here](${COMMIT_URL})"

                  # Send message to Telegram
                  curl -s -X POST "https://api.telegram.org/bot${TELEGRAM_TOKEN}/sendMessage" \
                  -d chat_id="${TELEGRAM_CHAT_ID}" \
                  -d text="${MESSAGE}" \
                  -d parse_mode="Markdown"
