name: Deploy to Server

on:
  push:
    branches:
      - master 

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup SSH agent
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }} # Thêm SSH private key vào GitHub Secrets

    - name: Copy files via SSH
      run: |
        scp -r ./ renthub@15.235.147.26:./home/renthouse/renthub/backend

    - name: Execute deploy script
      run: |
        ssh tmquang0209@gmail.com 'cd ./home/renthouse/renthub/backend && ./src/commands/deploy.sh'
